repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0  # or latest tag
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0  # latest stable version
    hooks:
      - id: detect-secrets
